<#--
 ========================LICENSE_START=================================
 Smooks Commons
 %%
 Copyright (C) 2020 Smooks
 %%
 Licensed under the terms of the Apache License Version 2.0 or,
 the GNU Lesser General Public License version 3.0 or later.
 
 SPDX-License-Identifier: Apache-2.0 OR LGPL-3.0-or-later
 
 ======================================================================
 
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 
     http://www.apache.org/licenses/LICENSE-2.0
 
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
 
 ======================================================================
 
 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 3 of the License, or (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 Lesser General Public License for more details.
 
 You should have received a copy of the GNU Lesser General Public License
 along with this program; if not, write to the Free Software Foundation,
 Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 =========================LICENSE_END==================================
-->
/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package ${class.packageName};

<#list class.imports as importClass>
import ${importClass.name};    
</#list>

<#list class.annotationTypes as annotationType>
@${annotationType.type.simpleName}    
</#list>
public class ${class.className}${class.implementsDecl}${class.extendsDecl} {

    <#if class.serializable>
    private static final long serialVersionUID = 1L;
    </#if>

    <#list class.properties as property>
    private ${property};
    </#list>
    <#list class.constructors as constructor>

    public ${class.className}${constructor.paramSignature} {
        ${constructor.body}
    }
    </#list>
    <#list class.methods as method>

    public ${method.returnType} ${method.methodName}${method.paramSignature} {
        ${method.body}
    }
    </#list>
}
