name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}
      GPG_OWNERTRUST: ${{ secrets.GPG_OWNERTRUST }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: |
          mvn install -pl !benchmark -B -Dmaven.javadoc.skip=true
          mvn javadoc:aggregate -pl !benchmark -DreportOutputDirectory=target/site/javadoc/v\${project.version} -DdestDir=smooks -B
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          echo $GPG_SECRET_KEYS | base64 --decode | gpg --import --no-tty --batch --yes
          echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
          mvn deploy -pl !benchmark --settings .mvn/settings.xml -Dgpg.skip=false -DskipTests=true -B